version: '2.3'
services:
  auth0-webhook-http:
    image: docker.elastic.co/observability/stream:v0.14.0@sha256:a108f4f782df597a4be3c426a3f9c00e58284f682811d45fd13d4686f2260125
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=http://elastic-agent:8383/auth0/logs
      - STREAM_WEBHOOK_HEADER=Authorization=abc123
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/auth0-ndjson.log
  auth0-webhook-https:
    image: docker.elastic.co/observability/stream:v0.14.0@sha256:a108f4f782df597a4be3c426a3f9c00e58284f682811d45fd13d4686f2260125
    volumes:
      - ./sample_logs:/sample_logs:ro
    environment:
      - STREAM_PROTOCOL=webhook
      - STREAM_ADDR=https://elastic-agent:8384/auth0/logs
      - STREAM_WEBHOOK_HEADER=Authorization=abc123
      - STREAM_INSECURE=true
    command: log --start-signal=SIGHUP --delay=5s /sample_logs/auth0-ndjson.log
