version: '2.3'
services:
  confluence-files:
    image: alpine
    volumes:
      - ./files:/sample_logs:ro
      - ${SERVICE_LOGS_DIR}:/var/log
    command: /bin/sh -c "cp /sample_logs/*.log /var/log/"
  confluence-api:
    image: docker.elastic.co/observability/stream:v0.14.0@sha256:a108f4f782df597a4be3c426a3f9c00e58284f682811d45fd13d4686f2260125
    ports:
      - 8080
    volumes:
      - ./files:/files:ro
    environment:
      PORT: 8080
    command:
      - http-server
      - --addr=:8080
      - --config=/files/config.yml
